### PR TITLE
Fix errors in Russian format messages

### PR DESCRIPTION
**Pull request by AlexMe951**
- fix regexp's in properties to process exceptional values (values ending with 11, 12, 13, 14) and to fix working with values ending with 1
- add tests for Russian locale

Fixes JodaOrg/joda-time#532

### CODE REVIEW

**Comment by AlexMe951** [comment]
#533 issue fix

**Comment by jodastephen** [comment]
Thanks

**Comment by jodastephen** [comment]
Would it be possible for you check ThreeTen-Extra too? (The data was derived from here) Thanks!
https://github.com/ThreeTen/threeten-extra/tree/master/src/main/resources/org/threeten/extra

**Comment by AlexMe951** [comment]
Yes, I will have a look

**Comment by AlexMe951** [comment]
Created PR for ThreeTen-Extra too

**Pull request merged**
