### PR TITLE
Add Hebrew localization

### PR DESCRIPTION
**Pull request by hb20007**
Create `messages_he.properties`. Using UTF-8 encoding. Thanks to Arihol for the translation.

This localization is not perfect because, in Hebrew, with the number "1", the word order need to be switched, but this does not seem to be possible. So, this is the best we can do.

### CODE REVIEW

**Review by Arihol — COMMENTED** [review]
Can you please change the space after the word “and” to a hyphen (-)?

**Comment by hb20007** [comment]
@Arihol I think I already did that:
Screenshot of change
Is there another one?

**Comment by Arihol** [comment]
Oh sorry I missed that. Thank you!!!

**Comment by Arihol** [comment]
Sorry for being a little picky…
The hyphen should come AFTER the ‘and’
>ו-
And not
>-ו

**Comment by hb20007** [comment]
@Arihol I created a new PR with the correct hyphen position. Thanks

**Comment by Arihol** [comment]
@hb20007 
Cheers
Sorry for the trouble

**Pull request closed without merging**
