### PR TITLE
Add slovak translation to messages_sk.properties

### PR DESCRIPTION
**Pull request by dombalaz**
This PR adds slovak translation as described in https://github.com/lichess-org/lila/issues/11634 and https://github.com/lichess-org/lila/issues/11623

### CODE REVIEW

**Comment by hb20007** [comment]
@dombalaz I see that your file includes non-ASCII characters like ý. All of the other files in this repository use Unicode encoding for such characters. However, when I downloaded the file I could see that the encoding was UTF-8 so perhaps it is okay. Maybe @jodastephen can comment on this.

**Comment by dombalaz** [comment]
> 

didn't realize that, I made changes so it is aligned with other translations

**Comment by orim15** [comment]
I wanted to start working on Slovak translation but then noticed this thread. So I take it there is no need anymore?

**Comment by hb20007** [comment]
@orim15 Yes, the Slovak translation is already done :)

**Comment by jodastephen** [comment]
Thanks

**Pull request merged**
