### PR TITLE
CI: add CIFuzz Github action

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR. 

Related issue in terms of fuzzing integration: https://github.com/JodaOrg/joda-time/issues/586 Since Joda-Time is stable, this PR is not for introducing new features but rather ensure no new PRs breaks the code.

This is a service offered by OSS-Fuzz where joda-time already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by jodastephen** [comment]
Hi, I'm trying to follow the [OSS scorecard](https://github.com/ossf/scorecard) recommendations.

Have you considered adding a `permissions:` block to the yaml file in the PR to clearly state what permissions are needed? As things stand this PR ties my repo to the master branch of another project. I'm sure you are trustworthy, but as it stands the PR adds risk. The scorecard recommends:

* adding a permissions block
* depending on a specific SHA of the CIFuzz, not master branch

Does this make sense?

**Comment by DavidKorczynski** [comment]
> block to the yaml file in the PR to clearly state what permissions are needed?

@jonathanmetzman do you know what's the minimal set of permission required by CIFuzz?

**Comment by DavidKorczynski** [comment]
I wasn't able to definitively extract the minimal set of permissions for this. However, some of the folks that focused on scorecards have this set of permissions for CIFuzz: https://github.com/step-security/secure-workflows/blob/53eac018adabda5f1468e9a8fc9534d0000528d7/knowledge-base/actions/google/oss-fuzz/infra/cifuzz/actions/run_fuzzers/action-security.yml

I applied the same here, as I suspect they will be doing a better than me for determining this.

**Review by jodastephen — APPROVED** [review]

**Comment by jodastephen** [comment]
Thanks for the extra work, looks good now

**Comment by jodastephen** [comment]
Spoke too soon, the workflow is invalid: https://github.com/JodaOrg/joda-time/actions/runs/3722190907

**Pull request merged**
