### PR TITLE
BikramSambatChronology

### PR DESCRIPTION
**Pull request by grzesiek2010**
Hi!

my name is Grzegorz and I'm an Android Developer. I work on [ODK Collect](https://github.com/opendatakit/collect) where we use this project. We already implemented Ethiopic/Coptic/Islamic calendars but our users want Bikram Sambat too.

I found this fork https://github.com/bishwash72/joda-time-BIS and decided to use it. I cleaned the code and added some tests.

@bishwash72 it's your repository and I cherry-picked your commit's. Could you review this pr? It would be good if you can provide more info like:
Was your solution tested/used by real users? Why didn't you created such a pr by yourself here? etc.

Maybe you want to improve it? add anything?

### CODE REVIEW

**Comment by jodastephen** [comment]
For licensing reasons, I'd want to hear from the original developer before considering this for inclusion. That said, I don't generally add things to Joda-Time any more, as users should be migrating to JSR-310 in Java 8 and later.

**Comment by bishwash72** [comment]
@grzesiek2010, @jodastephen, @lognaturel  I have no concern related to using my source code. The reason I have developed this is to use for my Bikaram Sambat calendar App which will be opensource and published to Play store soon.

**Comment by grzesiek2010** [comment]
@lognaturel I cherry-picked @bishwash72's commit (licensing) but it's at the and not before all others as you wanted because that commit contains changes in classes I refactored, renamed and there were conflicts.

**Comment by lognaturel** [comment]
Thanks for licensing the code, @bishwash72! It would probably be simpler and more accurate for you to directly add the licenses to your own fork and then for it to be pulled in to downstream forks like this one. Either way, though, we'll need to hear from @jodastephen before knowing how to proceed.

@jodastephen any new thoughts on what our best bet is?

**Comment by lognaturel** [comment]
Closing this sounds fine, @jodastephen, thanks for getting back to us. 

Last question if you can remember off the top of your head -- should it be possible to define a chronology without using private methods (that is, without having to maintain a fork) or not?

**Comment by jodastephen** [comment]
I thought it was, but I'm not sure anyone has ever tried. If you hit a problem with that, I'll certainly take a look.

**Pull request closed without merging**
