### PR TITLE
Add Greek localization

### PR DESCRIPTION
**Pull request by hb20007**
Created `messages_el.properties`. UTF-8 encoding used.

### CODE REVIEW

**Review by jodastephen — APPROVED** [review]
Thanks

**Comment by jodastephen** [comment]
As per #504 , UTF8 cannot be used

**Comment by hb20007** [comment]
@jodastephen Are you sure that the information in https://github.com/JodaOrg/joda-time/pull/504 is correct? It references https://github.com/JodaOrg/joda-time/issues/228 and there the issue is clearly explained that the problem was Latin-1 and the suggested solution was to use UTF-8 or Unicode encoding. Also, the Finnish translation was merged and it uses UTF-8 also.
Please let me know

**Comment by jodastephen** [comment]
#228 was a change to use Unicode escapes, not UTF8. The comment was
>  Encode properties files using unicode escapes [#228]
  The properties files are supposed to be loaded using ISO 8859-1 but Android seems to have issues with that.
  Re-encode the files using unicode escapes to sidestep the issue.

The actual code is
`ResourceBundle b = ResourceBundle.getBundle(BUNDLE_NAME, locale);`
which will use the standard `Properties` loader

So, yes, the files need to use Unicode escapes

**Comment by hb20007** [comment]
@jodastephen Thanks, I will create new PRs with Unicode escapes.

**Pull request closed without merging**
