### PR TITLE
Adding sq locale

### PR DESCRIPTION
**Pull request by ujdhesa**
Please add sq locale translation to the project. TIA!

### CODE REVIEW

**Comment by hb20007** [comment]
@ujdhesa, I see that you have some non-ASCII characters in the file. We need to use Unicode escapes in the place of those characters. For example: https://github.com/JodaOrg/joda-time/blob/main/src/main/java/org/joda/time/format/messages_da.properties

**Comment by hb20007** [comment]
@ujdhesa Also, the space at the end of line 3 shouldn't be there.

**Comment by ujdhesa** [comment]
@hb2000
Just to be sure, are  you talking about “ë” character?

**Comment by ujdhesa** [comment]
File edited to comply with your request, @hb20007 . Thank you!

**Comment by hb20007** [comment]
> File edited to comply with your request, @hb20007 . Thank you!

That doesn't look right. You need to use a Unicode escape. It will look like this: `\u9999`, where `9999` will actually be the Unicode hex value of this character.

**Comment by hb20007** [comment]
@ujdhesa Are you sure the uppercase U will work? (`\U`)

I am searching for documentation and I see that the U seems to be in lowercase everywhere. For example:

> A unicode escape sequence is a backslash followed by the letter 'u' followed by four hexadecimal digits (0-9a-fA-F).

**Comment by hb20007** [comment]
@ujdhesa Actually, I'm sure that this is the correct one: `\u00EB`

**Comment by ujdhesa** [comment]
@hb20007 Changed as per your request.

**Comment by hb20007** [comment]
> @hb20007 Changed as per your request.

You also need to remove the `+` sign...

**Review by jodastephen — APPROVED** [review]
Thanks!

**Pull request merged**
